apiVersion: v1
kind: ConfigMap
metadata: 
  name: my-db-config-map
  labels: 
    storage: my-db-storage
data: 
 DB_DRIVER_NAME_VALUE: com.mysql.cj.jdbc.Driver
 DB_HOST_SERVICE_NAME_VALUE: my-app-db-service
 DB_SCHEMA_VALUE: my-app
 DB_PORT_VALUE: "3306"
