apiVersion: v1
kind: PersistentVolume
metadata:
 name: my-db-pv
 labels: 
  name: my-db-pv
spec:
  capacity: 
   storage: 4Gi
  accessModes: 
   - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath: 
    path: /opt/mysql
